export const dataCartStock = [
  {
    id: 1,
    title: "Костюм для девочки",
    price: 599,
    oldPrice: 719,
    imgUrl: "./img/card-1.jpg",
    discount: 20,
  },
  {
    id: 2,
    title: "Яркая куртка",
    price: 999,
    oldPrice: false,
    imgUrl: "./img/card-2.jpg",
    discount: 10,
  },
  {
    id: 3,
    title: "Платье с длинным рукавовм",
    price: 699,
    oldPrice: 839,
    imgUrl: "./img/card-3.jpg",
    discount: false,
  },
  {
    id: 4,
    title: "Платье с цветочным узором",
    price: 899,
    oldPrice: false,
    imgUrl: "./img/card-4.jpg",
    discount: 20,
  },
  {
    id: 1,
    title: "Костюм для девочки",
    price: 599,
    oldPrice: 719,
    imgUrl: "./img/card-1.jpg",
    discount: 20,
  },
  {
    id: 2,
    title: "Яркая куртка",
    price: 999,
    oldPrice: false,
    imgUrl: "./img/card-2.jpg",
    discount: 10,
  },
];
